# Generated by Django 2.0.3 on 2018-03-30 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0002_auto_20180330_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='album',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='user',
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
