# Generated by Django 2.0.3 on 2018-03-30 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0005_auto_20180331_0226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('debut_at', models.DateField(blank=True, null=True)),
                ('agency', models.CharField(blank=True, max_length=100, null=True)),
                ('introduction', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AlterField(
            model_name='album',
            name='musician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musics.Musician'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
