# Generated by Django 2.0.3 on 2018-03-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0007_song_lyrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='release_at',
            field=models.DateField(),
        ),
    ]
